import Head from "next/head";
import { useState, useRef, useEffect } from "react";
import { v4 as uuid } from "uuid";

import ToDoList from "../components/ToDoList";
import Button from "../components/Button";

const KEY = "tasks";

export default function App() {
  const taskRef = useRef();
  const [tasks, setTasks] = useState([]);

  useEffect(() => {
    const storedTasks = JSON.parse(localStorage.getItem(KEY));
    storedTasks ? setTasks(storedTasks) : "";
  }, []);

  // Save tasks in local storage
  useEffect(() => {
    localStorage.setItem(KEY, JSON.stringify(tasks));
  }, [tasks]);

  const handleTaskAdd = () => {
    const description = taskRef.current.value;

    // If is a empty task, do nothing
    if (description === "") return;

    setTasks((prevTasks) => {
      return [...prevTasks, { id: uuid(), description, completed: false }];
    });

    taskRef.current.value = null;
  };

  const toggleTask = (id) => {
    const newTasks = [...tasks];
    const task = newTasks.find((task) => task.id === id);
    task.completed = !task.completed;
    setTasks(newTasks);
  };

  const handleClearTasks = () => {
    const newTasks = tasks.filter((task) => !task.completed);
    setTasks(newTasks);
  };

  return (
    <>
      <Head>
        <title>Task list 📝</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-zinc-100 min-h-screen">
        <h1 className="text-3xl text-center">Create your task list</h1>
        <div>
          <ToDoList tasks={tasks} toggleTask={toggleTask} />
          <input ref={taskRef} type="text" placeholder="Write a new task" />
          <Button variant="primary" onClick={handleTaskAdd}>
            Add
          </Button>
          <Button variant="secondary" onClick={handleClearTasks}>
            Clear completed
          </Button>
        </div>
      </main>
    </>
  );
}
